### ISSUE TITLE
FatEcto.FatContext generates a lot of warnings upon compilation

### ISSUE THREAD

**Issue by heyitsjames** [tanweerdev/fat_ecto#4]
Upon compiling `fat_ecto` for the first time, I get the following warnings:

```
==> fat_ecto
Compiling 25 files (.ex)
warning: function nil.all/1 is undefined (module nil is not available)
Found at 2 locations:
  lib/fat_ecto/context.ex:68
  lib/fat_ecto/paginator.ex:66

warning: function nil.all/2 is undefined (module nil is not available)
  lib/fat_ecto/context.ex:140

warning: function nil.delete/1 is undefined (module nil is not available)
  lib/fat_ecto/context.ex:116

warning: function nil.delete_all/1 is undefined (module nil is not available)
  lib/fat_ecto/context.ex:122

warning: function nil.get/2 is undefined (module nil is not available)
Found at 2 locations:
  lib/fat_ecto/context.ex:76
  lib/fat_ecto/context.ex:85

warning: function nil.get!/2 is undefined (module nil is not available)
  lib/fat_ecto/context.ex:72

warning: function nil.get_by/2 is undefined (module nil is not available)
  lib/fat_ecto/context.ex:96

warning: function nil.insert/1 is undefined (module nil is not available)
  lib/fat_ecto/context.ex:104

warning: function nil.one/1 is undefined (module nil is not available)
Found at 6 locations:
  lib/fat_ecto/context.ex:24
  lib/fat_ecto/context.ex:43
  lib/fat_ecto/context.ex:49
  lib/fat_ecto/context.ex:56
  lib/fat_ecto/paginator.ex:76
  lib/fat_ecto/query.ex:158

warning: function nil.preload/2 is undefined (module nil is not available)
Found at 5 locations:
  lib/fat_ecto/context.ex:68
  lib/fat_ecto/context.ex:78
  lib/fat_ecto/context.ex:86
  lib/fat_ecto/context.ex:97
  lib/fat_ecto/context.ex:141

warning: function nil.update/1 is undefined (module nil is not available)
  lib/fat_ecto/context.ex:111
```

I see that one can use this module by `use FatEcto.FatContext, repo: MyRepo`, but I'm not doing this as I don't need this module so it generates a lot of useless warnings. Any ideas?

**Comment by heyitsjames** [comment]
Also, you guys should _really_ tie Github releases to your hex.pm release versions. It's really hard to see what is in each release

**Comment by tanweerdev** [comment]
@heyitsjames I see 4 warnings which are due to repo not being available at compile in latest version and its totally fine for now. 
`warning: function nil.all/1 is undefined (module nil is not available)
  lib/fat_ecto/query.ex:217

warning: function nil.all/2 is undefined (module nil is not available)
  lib/fat_ecto/query.ex:201

warning: function nil.one/1 is undefined (module nil is not available)
  lib/fat_ecto/query.ex:187

warning: function nil.one/2 is undefined (module nil is not available)
  lib/fat_ecto/query.ex:205`
I haven't really worked on resolving these warning. at the end of April, you will see more docs and less warning. Library is pretty stable and its been tested in many projects(although in active development). You are also welcome to submit PR(s). Thanks

**Comment by tanweerdev** [comment]
> Also, you guys should really tie Github releases to your hex.pm release versions. It's really hard to see what is in each release
Sure. You are also welcome to submit PR
